# SPDX-FileCopyrightText: 2026 DAASI International GmbH <info@daasi.de>
# SPDX-License-Identifier: CC0-1.0

# Keep this ipaddr/secret combination so the healthcheck continues to work.
client localhost {
        ipaddr = 127.0.0.1
        secret = testing123
	require_message_authenticator = yes
}

client my_vpn_server {
	# NOTE FOR DOCKER USERS
	# Keep in mind that if used with the default network driver of Docker
	# (bridge), incoming IP addresses are instead those of that Docker
	# network. You could use those, but lose the IP adress as an
	# additional authentication factor.
	# The easiest way to get the "true" incoming IP address would be using
	# the "host" network driver. This means losing network isolation between
	# the container and the Docker host and connecting to eduMFA over an
	# exposed port.
	# If you find a (good) solution with Docker, feel free to share it in a
	# GitHub discussion.
        ipaddr = 0.0.0.0/0
        secret = mysecurelygeneratedsecret
	require_message_authenticator = yes
}
